// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: service/synchronization/synchronization.proto

package synchronization

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Synchronization_Create_FullMethodName    = "/synchronization.Synchronization/Create"
	Synchronization_List_FullMethodName      = "/synchronization.Synchronization/List"
	Synchronization_Flush_FullMethodName     = "/synchronization.Synchronization/Flush"
	Synchronization_Pause_FullMethodName     = "/synchronization.Synchronization/Pause"
	Synchronization_Resume_FullMethodName    = "/synchronization.Synchronization/Resume"
	Synchronization_Reset_FullMethodName     = "/synchronization.Synchronization/Reset"
	Synchronization_Terminate_FullMethodName = "/synchronization.Synchronization/Terminate"
)

// SynchronizationClient is the client API for Synchronization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Synchronization manages the lifecycle of synchronization sessions.
type SynchronizationClient interface {
	// Create creates a new session.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// List returns metadata for existing sessions.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Flush flushes sessions.
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	// Pause pauses sessions.
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error)
	// Resume resumes paused or disconnected sessions.
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
	// Reset resets sessions' histories.
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	// Terminate terminates sessions.
	Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
}

type synchronizationClient struct {
	cc grpc.ClientConnInterface
}

func NewSynchronizationClient(cc grpc.ClientConnInterface) SynchronizationClient {
	_ = "STUB: not implemented"
	return *new(SynchronizationClient)
}

func (c *synchronizationClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *synchronizationClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *synchronizationClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *synchronizationClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *synchronizationClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *synchronizationClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *synchronizationClient) Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SynchronizationServer is the server API for Synchronization service.
// All implementations must embed UnimplementedSynchronizationServer
// for forward compatibility.
//
// Synchronization manages the lifecycle of synchronization sessions.
type SynchronizationServer interface {
	// Create creates a new session.
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// List returns metadata for existing sessions.
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Flush flushes sessions.
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	// Pause pauses sessions.
	Pause(context.Context, *PauseRequest) (*PauseResponse, error)
	// Resume resumes paused or disconnected sessions.
	Resume(context.Context, *ResumeRequest) (*ResumeResponse, error)
	// Reset resets sessions' histories.
	Reset(context.Context, *ResetRequest) (*ResetResponse, error)
	// Terminate terminates sessions.
	Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error)
	mustEmbedUnimplementedSynchronizationServer()
}

// UnimplementedSynchronizationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSynchronizationServer struct{}

func (UnimplementedSynchronizationServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSynchronizationServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSynchronizationServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSynchronizationServer) Pause(context.Context, *PauseRequest) (*PauseResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSynchronizationServer) Resume(context.Context, *ResumeRequest) (*ResumeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSynchronizationServer) Reset(context.Context, *ResetRequest) (*ResetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSynchronizationServer) Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSynchronizationServer) mustEmbedUnimplementedSynchronizationServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedSynchronizationServer) testEmbeddedByValue() { _ = "STUB: not implemented"; return }

// UnsafeSynchronizationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SynchronizationServer will
// result in compilation errors.
type UnsafeSynchronizationServer interface {
	mustEmbedUnimplementedSynchronizationServer()
}

func RegisterSynchronizationServer(s grpc.ServiceRegistrar, srv SynchronizationServer) {
	_ = "STUB: not implemented"
	// If the following call panics, it indicates UnimplementedSynchronizationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _Synchronization_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Synchronization_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Synchronization_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Synchronization_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Synchronization_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Synchronization_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Synchronization_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Synchronization_ServiceDesc is the grpc.ServiceDesc for Synchronization service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Synchronization_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synchronization.Synchronization",
	HandlerType: (*SynchronizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Synchronization_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Synchronization_List_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _Synchronization_Flush_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _Synchronization_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Synchronization_Resume_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _Synchronization_Reset_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _Synchronization_Terminate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/synchronization/synchronization.proto",
}
