// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service/prompting/prompting.proto

package prompting

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HostRequest encodes either an initial request to perform prompt hosting or a
// follow-up response to a message or prompt.
type HostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AllowPrompts indicates whether or not the hoster will allow prompts. If
	// not, it will only receive message requests. This field may only be set on
	// the initial request.
	AllowPrompts bool `protobuf:"varint,1,opt,name=allowPrompts,proto3" json:"allowPrompts,omitempty"`
	// Response is the prompt response, if any. On the initial request, this
	// must be an empty string. When responding to a prompt, it may be any
	// value. When responding to a message, it must be an empty string.
	Response      string `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *HostRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*HostRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *HostRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use HostRequest.ProtoReflect.Descriptor instead.
func (*HostRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *HostRequest) GetAllowPrompts() bool { _ = "STUB: not implemented"; return false }

func (x *HostRequest) GetResponse() string { _ = "STUB: not implemented"; return "" }

// HostResponse encodes either an initial response to perform prompt hosting or
// a follow-up request for messaging or prompting.
type HostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier is the prompter identifier. It is only set in the initial
	// response sent after the initial request.
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// IsPrompt indicates if the response is requesting a prompt (as opposed to
	// simple message display).
	IsPrompt bool `protobuf:"varint,2,opt,name=isPrompt,proto3" json:"isPrompt,omitempty"`
	// Message is the message associated with the prompt or message.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *HostResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*HostResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *HostResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use HostResponse.ProtoReflect.Descriptor instead.
func (*HostResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *HostResponse) GetIdentifier() string { _ = "STUB: not implemented"; return "" }

func (x *HostResponse) GetIsPrompt() bool { _ = "STUB: not implemented"; return false }

func (x *HostResponse) GetMessage() string { _ = "STUB: not implemented"; return "" }

// PromptRequest encodes a request for prompting by a specific prompter.
type PromptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prompter is the prompter identifier.
	Prompter string `protobuf:"bytes,1,opt,name=prompter,proto3" json:"prompter,omitempty"`
	// Prompt is the prompt to present.
	Prompt        string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *PromptRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*PromptRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PromptRequest) GetPrompter() string { _ = "STUB: not implemented"; return "" }

func (x *PromptRequest) GetPrompt() string { _ = "STUB: not implemented"; return "" }

// PromptResponse encodes the response from a prompter.
type PromptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response is the response returned by the prompter.
	Response      string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *PromptResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*PromptResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PromptResponse) GetResponse() string { _ = "STUB: not implemented"; return "" }

var File_service_prompting_prompting_proto protoreflect.FileDescriptor

const file_service_prompting_prompting_proto_rawDesc = "" +
	"\n" +
	"!service/prompting/prompting.proto\x12\tprompting\"M\n" +
	"\vHostRequest\x12\"\n" +
	"\fallowPrompts\x18\x01 \x01(\bR\fallowPrompts\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\"d\n" +
	"\fHostResponse\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bisPrompt\x18\x02 \x01(\bR\bisPrompt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"C\n" +
	"\rPromptRequest\x12\x1a\n" +
	"\bprompter\x18\x01 \x01(\tR\bprompter\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\",\n" +
	"\x0ePromptResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2\x8b\x01\n" +
	"\tPrompting\x12=\n" +
	"\x04Host\x12\x16.prompting.HostRequest\x1a\x17.prompting.HostResponse\"\x00(\x010\x01\x12?\n" +
	"\x06Prompt\x12\x18.prompting.PromptRequest\x1a\x19.prompting.PromptResponse\"\x00B5Z3github.com/mutagen-io/mutagen/pkg/service/promptingb\x06proto3"

var (
	file_service_prompting_prompting_proto_rawDescOnce sync.Once
	file_service_prompting_prompting_proto_rawDescData []byte
)

func file_service_prompting_prompting_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_service_prompting_prompting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_prompting_prompting_proto_goTypes = []any{
	(*HostRequest)(nil),    // 0: prompting.HostRequest
	(*HostResponse)(nil),   // 1: prompting.HostResponse
	(*PromptRequest)(nil),  // 2: prompting.PromptRequest
	(*PromptResponse)(nil), // 3: prompting.PromptResponse
}
var file_service_prompting_prompting_proto_depIdxs = []int32{
	0, // 0: prompting.Prompting.Host:input_type -> prompting.HostRequest
	2, // 1: prompting.Prompting.Prompt:input_type -> prompting.PromptRequest
	1, // 2: prompting.Prompting.Host:output_type -> prompting.HostResponse
	3, // 3: prompting.Prompting.Prompt:output_type -> prompting.PromptResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                        { file_service_prompting_prompting_proto_init() }
func file_service_prompting_prompting_proto_init() { _ = "STUB: not implemented"; return }
