// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service/daemon/daemon.proto

package daemon

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *VersionRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*VersionRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type VersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO: Should we encapsulate these inside a Version message type, perhaps
	// in the mutagen package?
	Major         uint64 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint64 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         uint64 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	Tag           string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *VersionResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*VersionResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *VersionResponse) GetMajor() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *VersionResponse) GetMinor() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *VersionResponse) GetPatch() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *VersionResponse) GetTag() string { _ = "STUB: not implemented"; return "" }

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *TerminateRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*TerminateRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type TerminateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *TerminateResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*TerminateResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *TerminateResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use TerminateResponse.ProtoReflect.Descriptor instead.
func (*TerminateResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_service_daemon_daemon_proto protoreflect.FileDescriptor

const file_service_daemon_daemon_proto_rawDesc = "" +
	"\n" +
	"\x1bservice/daemon/daemon.proto\x12\x06daemon\"\x10\n" +
	"\x0eVersionRequest\"e\n" +
	"\x0fVersionResponse\x12\x14\n" +
	"\x05major\x18\x01 \x01(\x04R\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\x04R\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\x04R\x05patch\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\"\x12\n" +
	"\x10TerminateRequest\"\x13\n" +
	"\x11TerminateResponse2\x8a\x01\n" +
	"\x06Daemon\x12<\n" +
	"\aVersion\x12\x16.daemon.VersionRequest\x1a\x17.daemon.VersionResponse\"\x00\x12B\n" +
	"\tTerminate\x12\x18.daemon.TerminateRequest\x1a\x19.daemon.TerminateResponse\"\x00B2Z0github.com/mutagen-io/mutagen/pkg/service/daemonb\x06proto3"

var (
	file_service_daemon_daemon_proto_rawDescOnce sync.Once
	file_service_daemon_daemon_proto_rawDescData []byte
)

func file_service_daemon_daemon_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_service_daemon_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_daemon_daemon_proto_goTypes = []any{
	(*VersionRequest)(nil),    // 0: daemon.VersionRequest
	(*VersionResponse)(nil),   // 1: daemon.VersionResponse
	(*TerminateRequest)(nil),  // 2: daemon.TerminateRequest
	(*TerminateResponse)(nil), // 3: daemon.TerminateResponse
}
var file_service_daemon_daemon_proto_depIdxs = []int32{
	0, // 0: daemon.Daemon.Version:input_type -> daemon.VersionRequest
	2, // 1: daemon.Daemon.Terminate:input_type -> daemon.TerminateRequest
	1, // 2: daemon.Daemon.Version:output_type -> daemon.VersionResponse
	3, // 3: daemon.Daemon.Terminate:output_type -> daemon.TerminateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                  { file_service_daemon_daemon_proto_init() }
func file_service_daemon_daemon_proto_init() { _ = "STUB: not implemented"; return }
