// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: selection/selection.proto

package selection

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Selection encodes a selection mechanism that can be used to select a
// collection of sessions. It should have exactly one member set.
type Selection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All, if true, indicates that all sessions should be selected.
	All bool `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	// Specifications is a list of session specifications. Each element may be
	// either a session identifier or name (or a prefix thereof). If non-empty,
	// it indicates that these specifications should be used to select sessions.
	Specifications []string `protobuf:"bytes,2,rep,name=specifications,proto3" json:"specifications,omitempty"`
	// LabelSelector is a label selector specification. If present (non-empty),
	// it indicates that this selector should be used to select sessions.
	LabelSelector string `protobuf:"bytes,3,opt,name=labelSelector,proto3" json:"labelSelector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() { _ = "STUB: not implemented"; return }

func (x *Selection) String() string { _ = "STUB: not implemented"; return "" }

func (*Selection) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Selection) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Selection) GetAll() bool { _ = "STUB: not implemented"; return false }

func (x *Selection) GetSpecifications() []string { _ = "STUB: not implemented"; return nil }

func (x *Selection) GetLabelSelector() string { _ = "STUB: not implemented"; return "" }

var File_selection_selection_proto protoreflect.FileDescriptor

const file_selection_selection_proto_rawDesc = "" +
	"\n" +
	"\x19selection/selection.proto\x12\tselection\"k\n" +
	"\tSelection\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12&\n" +
	"\x0especifications\x18\x02 \x03(\tR\x0especifications\x12$\n" +
	"\rlabelSelector\x18\x03 \x01(\tR\rlabelSelectorB-Z+github.com/mutagen-io/mutagen/pkg/selectionb\x06proto3"

var (
	file_selection_selection_proto_rawDescOnce sync.Once
	file_selection_selection_proto_rawDescData []byte
)

func file_selection_selection_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_selection_selection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_selection_selection_proto_goTypes = []any{
	(*Selection)(nil), // 0: selection.Selection
}
var file_selection_selection_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                { file_selection_selection_proto_init() }
func file_selection_selection_proto_init() { _ = "STUB: not implemented"; return }
