// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: url/url.proto

package url

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind indicates the kind of a URL.
type Kind int32

const (
	// Synchronization indicates a synchronization URL.
	Kind_Synchronization Kind = 0
	// Forwarding indicates a forwarding URL.
	Kind_Forwarding Kind = 1
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "Synchronization",
		1: "Forwarding",
	}
	Kind_value = map[string]int32{
		"Synchronization": 0,
		"Forwarding":      1,
	}
)

func (x Kind) Enum() *Kind { _ = "STUB: not implemented"; return nil }

func (x Kind) String() string { _ = "STUB: not implemented"; return "" }

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Kind) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Kind) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Protocol indicates a location type.
type Protocol int32

const (
	// Local indicates that the resource is on the local system.
	Protocol_Local Protocol = 0
	// SSH indicates that the resource is accessible via SSH.
	Protocol_SSH Protocol = 1
	// Docker indicates that the resource is inside a Docker container.
	Protocol_Docker Protocol = 11
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0:  "Local",
		1:  "SSH",
		11: "Docker",
	}
	Protocol_value = map[string]int32{
		"Local":  0,
		"SSH":    1,
		"Docker": 11,
	}
)

func (x Protocol) Enum() *Protocol { _ = "STUB: not implemented"; return nil }

func (x Protocol) String() string { _ = "STUB: not implemented"; return "" }

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Protocol) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Protocol) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// URL represents a pointer to a resource. It should be considered immutable.
type URL struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind indicates the URL kind.
	// NOTE: This field number is out of order for historical reasons.
	Kind Kind `protobuf:"varint,7,opt,name=kind,proto3,enum=url.Kind" json:"kind,omitempty"`
	// Protocol indicates a location type.
	Protocol Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=url.Protocol" json:"protocol,omitempty"`
	// User is the user under which a resource should be accessed.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Host is protocol-specific, but generally indicates the location of the
	// remote.
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// Port indicates a TCP port via which to access the remote location, if
	// applicable.
	Port uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// Path indicates the path of a resource.
	Path string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	// Environment contains captured environment variable information. It is not
	// a required component and its contents and their behavior depend on the
	// transport implementation.
	Environment map[string]string `protobuf:"bytes,6,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Parameters are internal transport parameters. These are set for URLs
	// generated internally that require additional metadata. Parameters are not
	// required and their behavior is dependent on the transport implementation.
	Parameters    map[string]string `protobuf:"bytes,8,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL) Reset() { _ = "STUB: not implemented"; return }

func (x *URL) String() string { _ = "STUB: not implemented"; return "" }

func (*URL) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *URL) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *URL) GetKind() Kind { _ = "STUB: not implemented"; return *new(Kind) }

func (x *URL) GetProtocol() Protocol { _ = "STUB: not implemented"; return *new(Protocol) }

func (x *URL) GetUser() string { _ = "STUB: not implemented"; return "" }

func (x *URL) GetHost() string { _ = "STUB: not implemented"; return "" }

func (x *URL) GetPort() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *URL) GetPath() string { _ = "STUB: not implemented"; return "" }

func (x *URL) GetEnvironment() map[string]string { _ = "STUB: not implemented"; return nil }

func (x *URL) GetParameters() map[string]string { _ = "STUB: not implemented"; return nil }

var File_url_url_proto protoreflect.FileDescriptor

const file_url_url_proto_rawDesc = "" +
	"\n" +
	"\rurl/url.proto\x12\x03url\"\x95\x03\n" +
	"\x03URL\x12\x1d\n" +
	"\x04kind\x18\a \x01(\x0e2\t.url.KindR\x04kind\x12)\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\r.url.ProtocolR\bprotocol\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12;\n" +
	"\venvironment\x18\x06 \x03(\v2\x19.url.URL.EnvironmentEntryR\venvironment\x128\n" +
	"\n" +
	"parameters\x18\b \x03(\v2\x18.url.URL.ParametersEntryR\n" +
	"parameters\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*+\n" +
	"\x04Kind\x12\x13\n" +
	"\x0fSynchronization\x10\x00\x12\x0e\n" +
	"\n" +
	"Forwarding\x10\x01**\n" +
	"\bProtocol\x12\t\n" +
	"\x05Local\x10\x00\x12\a\n" +
	"\x03SSH\x10\x01\x12\n" +
	"\n" +
	"\x06Docker\x10\vB'Z%github.com/mutagen-io/mutagen/pkg/urlb\x06proto3"

var (
	file_url_url_proto_rawDescOnce sync.Once
	file_url_url_proto_rawDescData []byte
)

func file_url_url_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_url_url_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_url_url_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_url_url_proto_goTypes = []any{
	(Kind)(0),     // 0: url.Kind
	(Protocol)(0), // 1: url.Protocol
	(*URL)(nil),   // 2: url.URL
	nil,           // 3: url.URL.EnvironmentEntry
	nil,           // 4: url.URL.ParametersEntry
}
var file_url_url_proto_depIdxs = []int32{
	0, // 0: url.URL.kind:type_name -> url.Kind
	1, // 1: url.URL.protocol:type_name -> url.Protocol
	3, // 2: url.URL.environment:type_name -> url.URL.EnvironmentEntry
	4, // 3: url.URL.parameters:type_name -> url.URL.ParametersEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init()                    { file_url_url_proto_init() }
func file_url_url_proto_init() { _ = "STUB: not implemented"; return }
