// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/core/ignore/ignore_vcs_mode.proto

package ignore

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IgnoreVCSMode specifies the mode for ignoring VCS directories.
type IgnoreVCSMode int32

const (
	// IgnoreVCSMode_IgnoreVCSModeDefault represents an unspecified VCS ignore
	// mode. It is not valid for use with Scan. It should be converted to one of
	// the following values based on the desired default behavior.
	IgnoreVCSMode_IgnoreVCSModeDefault IgnoreVCSMode = 0
	// IgnoreVCSMode_IgnoreVCSModeIgnore indicates that VCS directories should
	// be ignored.
	IgnoreVCSMode_IgnoreVCSModeIgnore IgnoreVCSMode = 1
	// IgnoreVCSMode_IgnoreVCSModePropagate indicates that VCS directories
	// should be propagated.
	IgnoreVCSMode_IgnoreVCSModePropagate IgnoreVCSMode = 2
)

// Enum value maps for IgnoreVCSMode.
var (
	IgnoreVCSMode_name = map[int32]string{
		0: "IgnoreVCSModeDefault",
		1: "IgnoreVCSModeIgnore",
		2: "IgnoreVCSModePropagate",
	}
	IgnoreVCSMode_value = map[string]int32{
		"IgnoreVCSModeDefault":   0,
		"IgnoreVCSModeIgnore":    1,
		"IgnoreVCSModePropagate": 2,
	}
)

func (x IgnoreVCSMode) Enum() *IgnoreVCSMode { _ = "STUB: not implemented"; return nil }

func (x IgnoreVCSMode) String() string { _ = "STUB: not implemented"; return "" }

func (IgnoreVCSMode) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (IgnoreVCSMode) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x IgnoreVCSMode) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use IgnoreVCSMode.Descriptor instead.
func (IgnoreVCSMode) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_synchronization_core_ignore_ignore_vcs_mode_proto protoreflect.FileDescriptor

const file_synchronization_core_ignore_ignore_vcs_mode_proto_rawDesc = "" +
	"\n" +
	"1synchronization/core/ignore/ignore_vcs_mode.proto\x12\x06ignore*^\n" +
	"\rIgnoreVCSMode\x12\x18\n" +
	"\x14IgnoreVCSModeDefault\x10\x00\x12\x17\n" +
	"\x13IgnoreVCSModeIgnore\x10\x01\x12\x1a\n" +
	"\x16IgnoreVCSModePropagate\x10\x02B?Z=github.com/mutagen-io/mutagen/pkg/synchronization/core/ignoreb\x06proto3"

var (
	file_synchronization_core_ignore_ignore_vcs_mode_proto_rawDescOnce sync.Once
	file_synchronization_core_ignore_ignore_vcs_mode_proto_rawDescData []byte
)

func file_synchronization_core_ignore_ignore_vcs_mode_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_core_ignore_ignore_vcs_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_core_ignore_ignore_vcs_mode_proto_goTypes = []any{
	(IgnoreVCSMode)(0), // 0: ignore.IgnoreVCSMode
}
var file_synchronization_core_ignore_ignore_vcs_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_synchronization_core_ignore_ignore_vcs_mode_proto_init() }
func file_synchronization_core_ignore_ignore_vcs_mode_proto_init() {
	_ = "STUB: not implemented"
	return
}
