// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/core/ignore/syntax.proto

package ignore

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Syntax specifies the syntax and semantics for ignore specifications.
type Syntax int32

const (
	// Syntax_SyntaxDefault represents an unspecified ignore syntax. It is not
	// valid for use with core synchronization functions. It should be converted
	// to one of the following values based on the desired default behavior.
	Syntax_SyntaxDefault Syntax = 0
	// Syntax_SyntaxMutagen specifies that Mutagen-style ignore syntax and
	// semantics should be used.
	Syntax_SyntaxMutagen Syntax = 1
	// Syntax_SyntaxDocker specifies that Docker-style ignore syntax and
	// semantics should be used.
	Syntax_SyntaxDocker Syntax = 2
)

// Enum value maps for Syntax.
var (
	Syntax_name = map[int32]string{
		0: "SyntaxDefault",
		1: "SyntaxMutagen",
		2: "SyntaxDocker",
	}
	Syntax_value = map[string]int32{
		"SyntaxDefault": 0,
		"SyntaxMutagen": 1,
		"SyntaxDocker":  2,
	}
)

func (x Syntax) Enum() *Syntax { _ = "STUB: not implemented"; return nil }

func (x Syntax) String() string { _ = "STUB: not implemented"; return "" }

func (Syntax) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Syntax) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Syntax) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Syntax.Descriptor instead.
func (Syntax) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_synchronization_core_ignore_syntax_proto protoreflect.FileDescriptor

const file_synchronization_core_ignore_syntax_proto_rawDesc = "" +
	"\n" +
	"(synchronization/core/ignore/syntax.proto\x12\x06ignore*@\n" +
	"\x06Syntax\x12\x11\n" +
	"\rSyntaxDefault\x10\x00\x12\x11\n" +
	"\rSyntaxMutagen\x10\x01\x12\x10\n" +
	"\fSyntaxDocker\x10\x02B?Z=github.com/mutagen-io/mutagen/pkg/synchronization/core/ignoreb\x06proto3"

var (
	file_synchronization_core_ignore_syntax_proto_rawDescOnce sync.Once
	file_synchronization_core_ignore_syntax_proto_rawDescData []byte
)

func file_synchronization_core_ignore_syntax_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_core_ignore_syntax_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_core_ignore_syntax_proto_goTypes = []any{
	(Syntax)(0), // 0: ignore.Syntax
}
var file_synchronization_core_ignore_syntax_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                               { file_synchronization_core_ignore_syntax_proto_init() }
func file_synchronization_core_ignore_syntax_proto_init() { _ = "STUB: not implemented"; return }
