// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/core/archive.proto

package core

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Archive is a wrapper that distinguishes between a nil Entry and a zero-valued
// Entry when serializing. This is necessary because Protocol Buffers will
// encode both a nil Entry and a zero-valued Entry as an empty byte slice if
// they are the root message that's being serialized. Adding a level of
// indirection allows for a distinction in encoding between an absence of
// content and an empty directory.
type Archive struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content is the entry stored in the archive. It may be nil to indicate an
	// absence of content.
	Content       *Entry `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Archive) Reset() { _ = "STUB: not implemented"; return }

func (x *Archive) String() string { _ = "STUB: not implemented"; return "" }

func (*Archive) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Archive) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Archive.ProtoReflect.Descriptor instead.
func (*Archive) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Archive) GetContent() *Entry { _ = "STUB: not implemented"; return nil }

var File_synchronization_core_archive_proto protoreflect.FileDescriptor

const file_synchronization_core_archive_proto_rawDesc = "" +
	"\n" +
	"\"synchronization/core/archive.proto\x12\x04core\x1a synchronization/core/entry.proto\"0\n" +
	"\aArchive\x12%\n" +
	"\acontent\x18\x01 \x01(\v2\v.core.EntryR\acontentB8Z6github.com/mutagen-io/mutagen/pkg/synchronization/coreb\x06proto3"

var (
	file_synchronization_core_archive_proto_rawDescOnce sync.Once
	file_synchronization_core_archive_proto_rawDescData []byte
)

func file_synchronization_core_archive_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_core_archive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_synchronization_core_archive_proto_goTypes = []any{
	(*Archive)(nil), // 0: core.Archive
	(*Entry)(nil),   // 1: core.Entry
}
var file_synchronization_core_archive_proto_depIdxs = []int32{
	1, // 0: core.Archive.content:type_name -> core.Entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init()                                         { file_synchronization_core_archive_proto_init() }
func file_synchronization_core_archive_proto_init() { _ = "STUB: not implemented"; return }
