// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/core/change.proto

package core

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Change encodes a change to an entry hierarchy. Change objects should be
// considered immutable and must not be modified.
type Change struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path is the path of the root of the change (relative to the
	// synchronization root).
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Old represents the old filesystem hierarchy at the change path. It may be
	// nil if no content previously existed.
	Old *Entry `protobuf:"bytes,2,opt,name=old,proto3" json:"old,omitempty"`
	// New represents the new filesystem hierarchy at the change path. It may be
	// nil if content has been deleted.
	New           *Entry `protobuf:"bytes,3,opt,name=new,proto3" json:"new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() { _ = "STUB: not implemented"; return }

func (x *Change) String() string { _ = "STUB: not implemented"; return "" }

func (*Change) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Change) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Change) GetPath() string { _ = "STUB: not implemented"; return "" }

func (x *Change) GetOld() *Entry { _ = "STUB: not implemented"; return nil }

func (x *Change) GetNew() *Entry { _ = "STUB: not implemented"; return nil }

var File_synchronization_core_change_proto protoreflect.FileDescriptor

const file_synchronization_core_change_proto_rawDesc = "" +
	"\n" +
	"!synchronization/core/change.proto\x12\x04core\x1a synchronization/core/entry.proto\"Z\n" +
	"\x06Change\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\x03old\x18\x02 \x01(\v2\v.core.EntryR\x03old\x12\x1d\n" +
	"\x03new\x18\x03 \x01(\v2\v.core.EntryR\x03newB8Z6github.com/mutagen-io/mutagen/pkg/synchronization/coreb\x06proto3"

var (
	file_synchronization_core_change_proto_rawDescOnce sync.Once
	file_synchronization_core_change_proto_rawDescData []byte
)

func file_synchronization_core_change_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_core_change_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_synchronization_core_change_proto_goTypes = []any{
	(*Change)(nil), // 0: core.Change
	(*Entry)(nil),  // 1: core.Entry
}
var file_synchronization_core_change_proto_depIdxs = []int32{
	1, // 0: core.Change.old:type_name -> core.Entry
	1, // 1: core.Change.new:type_name -> core.Entry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init()                                        { file_synchronization_core_change_proto_init() }
func file_synchronization_core_change_proto_init() { _ = "STUB: not implemented"; return }
