// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/core/permissions_mode.proto

package core

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PermissionsMode specifies the mode for handling permission propagation.
type PermissionsMode int32

const (
	// PermissionsMode_PermissionsModeDefault represents an unspecified
	// permissions mode. It is not valid for use with Scan. It should be
	// converted to one of the following values based on the desired default
	// behavior.
	PermissionsMode_PermissionsModeDefault PermissionsMode = 0
	// PermissionsMode_PermissionsModePortable specifies that permissions should
	// be propagated in a portable fashion. This means that only executability
	// bits are managed by Mutagen and that manual specifications for ownership
	// and base file permissions are used.
	PermissionsMode_PermissionsModePortable PermissionsMode = 1
	// PermissionsMode_PermissionsModeManual specifies that only manual
	// permission specifications should be used. In this case, Mutagen does not
	// perform any propagation of permissions.
	PermissionsMode_PermissionsModeManual PermissionsMode = 2
)

// Enum value maps for PermissionsMode.
var (
	PermissionsMode_name = map[int32]string{
		0: "PermissionsModeDefault",
		1: "PermissionsModePortable",
		2: "PermissionsModeManual",
	}
	PermissionsMode_value = map[string]int32{
		"PermissionsModeDefault":  0,
		"PermissionsModePortable": 1,
		"PermissionsModeManual":   2,
	}
)

func (x PermissionsMode) Enum() *PermissionsMode { _ = "STUB: not implemented"; return nil }

func (x PermissionsMode) String() string { _ = "STUB: not implemented"; return "" }

func (PermissionsMode) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (PermissionsMode) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x PermissionsMode) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use PermissionsMode.Descriptor instead.
func (PermissionsMode) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_synchronization_core_permissions_mode_proto protoreflect.FileDescriptor

const file_synchronization_core_permissions_mode_proto_rawDesc = "" +
	"\n" +
	"+synchronization/core/permissions_mode.proto\x12\x04core*e\n" +
	"\x0fPermissionsMode\x12\x1a\n" +
	"\x16PermissionsModeDefault\x10\x00\x12\x1b\n" +
	"\x17PermissionsModePortable\x10\x01\x12\x19\n" +
	"\x15PermissionsModeManual\x10\x02B8Z6github.com/mutagen-io/mutagen/pkg/synchronization/coreb\x06proto3"

var (
	file_synchronization_core_permissions_mode_proto_rawDescOnce sync.Once
	file_synchronization_core_permissions_mode_proto_rawDescData []byte
)

func file_synchronization_core_permissions_mode_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_core_permissions_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_core_permissions_mode_proto_goTypes = []any{
	(PermissionsMode)(0), // 0: core.PermissionsMode
}
var file_synchronization_core_permissions_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                                  { file_synchronization_core_permissions_mode_proto_init() }
func file_synchronization_core_permissions_mode_proto_init() { _ = "STUB: not implemented"; return }
