// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/core/problem.proto

package core

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Problem indicates an issue or error encountered at some stage of a
// synchronization cycle. Problem objects should be considered immutable and
// must not be modified.
type Problem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path is the path at which the problem occurred (relative to the
	// synchronization root).
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Error is a human-readable summary of the problem.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Problem) Reset() { _ = "STUB: not implemented"; return }

func (x *Problem) String() string { _ = "STUB: not implemented"; return "" }

func (*Problem) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Problem) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Problem) GetPath() string { _ = "STUB: not implemented"; return "" }

func (x *Problem) GetError() string { _ = "STUB: not implemented"; return "" }

var File_synchronization_core_problem_proto protoreflect.FileDescriptor

const file_synchronization_core_problem_proto_rawDesc = "" +
	"\n" +
	"\"synchronization/core/problem.proto\x12\x04core\"3\n" +
	"\aProblem\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorB8Z6github.com/mutagen-io/mutagen/pkg/synchronization/coreb\x06proto3"

var (
	file_synchronization_core_problem_proto_rawDescOnce sync.Once
	file_synchronization_core_problem_proto_rawDescData []byte
)

func file_synchronization_core_problem_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_core_problem_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_synchronization_core_problem_proto_goTypes = []any{
	(*Problem)(nil), // 0: core.Problem
}
var file_synchronization_core_problem_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                         { file_synchronization_core_problem_proto_init() }
func file_synchronization_core_problem_proto_init() { _ = "STUB: not implemented"; return }
