package core

// EnsureValid ensures that Snapshot's invariants are respected.
func (s *Snapshot) EnsureValid() error {
	_ = "STUB: not implemented"
	// A nil snapshot is not valid.
	return nil
}

// Ensure that the snapshot content is valid. Snapshots may naturally
// contain unsynchronizable content.

// All values of behavioral metadata fields are valid.

// While there are some validations that we could perform on the statistical
// fields of the snapshot, they don't exhaustively determine validity.
// Moreover, some of these might be expensive, such as comparing the static
// entry counts with those generated by the content entry. On the whole,
// since the statistical fields are only used for informational purposes,
// and since they are all valid from a memory-safety perspective, there's no
// point in validating them.

// Success.

// Equal performs an equivalence comparison between this snapshot and another.
func (s *Snapshot) Equal(other *Snapshot) bool { _ = "STUB: not implemented"; return false }
