// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/core/snapshot.proto

package core

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Snapshot bundles a filesystem content snapshot with associated metadata.
// Snapshot objects should be considered immutable and must not be modified.
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content is the filesystem content at the snapshot root. It may be nil to
	// indicate an absence of content.
	Content *Entry `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// PreservesExecutability indicates whether or not the associated filesystem
	// preserves POSIX executability bits.
	PreservesExecutability bool `protobuf:"varint,2,opt,name=preservesExecutability,proto3" json:"preservesExecutability,omitempty"`
	// DecomposesUnicode indicates whether or not the associated filesystem
	// decomposes Unicode names.
	DecomposesUnicode bool `protobuf:"varint,3,opt,name=decomposesUnicode,proto3" json:"decomposesUnicode,omitempty"`
	// Directories is the number of synchronizable directory entries contained
	// in the snapshot.
	Directories uint64 `protobuf:"varint,4,opt,name=directories,proto3" json:"directories,omitempty"`
	// Files is the number of synchronizable file entries contained in the
	// snapshot.
	Files uint64 `protobuf:"varint,5,opt,name=files,proto3" json:"files,omitempty"`
	// SymbolicLinks is the number of synchronizable symbolic link entries
	// contained in the snapshot.
	SymbolicLinks uint64 `protobuf:"varint,6,opt,name=symbolicLinks,proto3" json:"symbolicLinks,omitempty"`
	// TotalFileSize is the total size of all synchronizable files referenced by
	// the snapshot.
	TotalFileSize uint64 `protobuf:"varint,7,opt,name=totalFileSize,proto3" json:"totalFileSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() { _ = "STUB: not implemented"; return }

func (x *Snapshot) String() string { _ = "STUB: not implemented"; return "" }

func (*Snapshot) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Snapshot) GetContent() *Entry { _ = "STUB: not implemented"; return nil }

func (x *Snapshot) GetPreservesExecutability() bool { _ = "STUB: not implemented"; return false }

func (x *Snapshot) GetDecomposesUnicode() bool { _ = "STUB: not implemented"; return false }

func (x *Snapshot) GetDirectories() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *Snapshot) GetFiles() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *Snapshot) GetSymbolicLinks() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *Snapshot) GetTotalFileSize() uint64 { _ = "STUB: not implemented"; return 0 }

var File_synchronization_core_snapshot_proto protoreflect.FileDescriptor

const file_synchronization_core_snapshot_proto_rawDesc = "" +
	"\n" +
	"#synchronization/core/snapshot.proto\x12\x04core\x1a synchronization/core/entry.proto\"\x9b\x02\n" +
	"\bSnapshot\x12%\n" +
	"\acontent\x18\x01 \x01(\v2\v.core.EntryR\acontent\x126\n" +
	"\x16preservesExecutability\x18\x02 \x01(\bR\x16preservesExecutability\x12,\n" +
	"\x11decomposesUnicode\x18\x03 \x01(\bR\x11decomposesUnicode\x12 \n" +
	"\vdirectories\x18\x04 \x01(\x04R\vdirectories\x12\x14\n" +
	"\x05files\x18\x05 \x01(\x04R\x05files\x12$\n" +
	"\rsymbolicLinks\x18\x06 \x01(\x04R\rsymbolicLinks\x12$\n" +
	"\rtotalFileSize\x18\a \x01(\x04R\rtotalFileSizeB8Z6github.com/mutagen-io/mutagen/pkg/synchronization/coreb\x06proto3"

var (
	file_synchronization_core_snapshot_proto_rawDescOnce sync.Once
	file_synchronization_core_snapshot_proto_rawDescData []byte
)

func file_synchronization_core_snapshot_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_core_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_synchronization_core_snapshot_proto_goTypes = []any{
	(*Snapshot)(nil), // 0: core.Snapshot
	(*Entry)(nil),    // 1: core.Entry
}
var file_synchronization_core_snapshot_proto_depIdxs = []int32{
	1, // 0: core.Snapshot.content:type_name -> core.Entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init()                                          { file_synchronization_core_snapshot_proto_init() }
func file_synchronization_core_snapshot_proto_init() { _ = "STUB: not implemented"; return }
