//go:build linux && mutagensspl

// Copyright (c) 2020-present Docker, Inc.
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the Server Side Public License, version 1, as published by
// MongoDB, Inc.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the Server Side Public License for more
// details.
//
// You should have received a copy of the Server Side Public License along with
// this program. If not, see
// <http://www.mongodb.com/licensing/server-side-public-license>.

package fanotify

import (
	"context"
	"errors"
	"io"
	"sync"
)

var (
	// ErrWatchInternalOverflow indicates that a watcher saw an event buffering
	// overflow in its underlying watching mechanism.
	ErrWatchInternalOverflow = errors.New("internal event overflow")
	// ErrWatchTerminated indicates that a watcher has been terminated.
	ErrWatchTerminated = errors.New("watch terminated")
)

// RecursiveWatcher implements watching.RecursiveWatcher using fanotify.
type RecursiveWatcher struct {
	// watch is a handle for closing the underlying fanotify watch descriptor.
	watch io.Closer
	// events is the event delivery channel.
	events chan string
	// writeErrorOnce ensures that only one error is written to errors.
	writeErrorOnce sync.Once
	// errors is the error delivery channel.
	errors chan error
	// cancel is the run loop cancellation function.
	cancel context.CancelFunc
	// done is the run loop completion signaling mechanism.
	done sync.WaitGroup
}

// NewRecursiveWatcher creates a new fanotify-based recursive watcher using the
// specified target path.
func NewRecursiveWatcher(target string) (*RecursiveWatcher, error) {
	_ = "STUB: not implemented"
	// Enforce that the watch target path is absolute. This is necessary for our
	// invocation of fanotify_mark and to adjust incoming event paths to be
	// relative to the watch target.
	return nil, nil
}

// TODO: It's unclear if we want to perform symbolic link evaluation here
// like we do in other watchers. If we do, then we may want to make
// adjustments to our open and fanotify_mark calls below. At the moment,
// it's irrelevant to our very controlled use case. If we do perform
// symbolic link evaluation, then we can remove the filepath.Clean call.

// Ensure that the target is cleaned. This is necessary for adjusting event
// paths to be target-relative.

// Determine the mount point for the path.

// Get a file descriptor for the mount point to use with open_by_handle_at.
// Despite the claim in the Linux open(2) man page, it doesn't appear that
// O_PATH returns a file descriptor suitable for use with all *at functions.
// Specifically, it doesn't work with open_by_handle_at, and thus we need to
// perform a "full" open operation.

// Create an fanotify watch capable of detecting file events (i.e. using
// FAN_REPORT_FID). We set the descriptor for this watch to be non-blocking
// so that we can use an os.File to poll on it and enable read cancellation.
// The fanotify documentation explicitly states that this descriptor is
// compatible with epoll, poll, and select, so we know it will work with the
// Go poller. Also, because we're using FAN_REPORT_FID, we won't receive
// file descriptors automatically and thus don't need to provide flags for
// their construction.

// Add the target path to the watch. We notably exclude FAN_DELETE_SELF from
// our event mask because it is (almost) always accompanied by a stale file
// handle from which we cannot obtain a corresponding path. In rare cases
// (that come down to race conditions), it is possible to open a deleted
// file by its handle before it is fully removed from the filesystem, but
// the path will have " (deleted)" appended by the kernel. In any case, we
// don't need the deleted path when using accelerated scanning, only its
// parent path (which will come from the FAN_DELETE event). However, we do
// need FAN_MOVE_SELF, because FAN_MOVE alone will only tell accelerated
// scanning to rescan the parent, which in the case of file replacement on
// move wouldn't detect changes to the replaced file. We also exclude
// FAN_CLOSE_WRITE because it is generated in conjunction with a FAN_MODIFY
// event (which we already watch for) if changes are flushed to disk on
// closure, so we can skip it and avoid spurious events generated by closure
// of unmodified writable files. Also, despite what the documentation says,
// FAN_Q_OVERFLOW should not be specified as part of this mask, otherwise
// EINVAL will be returned. The generation of overflow events is automatic.

// Convert the watch descriptor to an os.File so that it's pollable.

// Create a context to regulate the watcher's polling and run loops.

// Create the watcher.

// Track run loop termination.

// Start the run loop.

// Success.

// run implements the event processing run loop for RecursiveWatcher.
func (w *RecursiveWatcher) run(ctx context.Context, watch io.Reader, mountDescriptor int, target string) error {
	_ = "STUB: not implemented"
	// Compute the prefix that we'll need to trim from event paths to make them
	// target-relative (if they aren't the target itself). We know that target
	// will be clean, and thus lacking a trailing slash (unless it's the system
	// root path).
	return nil
}

// Loop until cancellation or a read error occurs.

// Read the next group of events. Note that the fanotify API will only
// return whole events into the buffer, so there's no need to worry
// about partial event reads.

// Process the events.

// Process a single event.

// If the path was stale, then just ignore it.

// Convert the event path to be target-relative. We have to ignore
// anything that doesn't fall at or below our watch target for two
// reasons:
//
// First, our watch and path resolution location is the mount point,
// not necessarily the watch target. Much like on Windows, we have
// to watch outside of the target in order to ensure a stable watch
// and to ensure that we're seeing changes to the target itself
// (though, in this case, we do it more for stability since we know
// the volume mounts aren't likely to disappear).
//
// Second, with fanotify, we're watching an entire filesystem, and
// thus we may see events that occur outside of the mount point that
// we're watching, especially if that mount point isn't mounting the
// filesystem root. If the event can't be referenced by a path
// beneath the mount point that we're using with open_by_handle_at,
// then a read of its path will result in "/". For example, watching
// container volumes that are just bind-mounted directories from the
// host filesystem will result in a watch of the entire host
// filesystem, but a modification to a path outside of the volume
// directory on the host filesystem will yield a notification with
// a path resolving to "/" (when resolved relative to the mount
// point). This is basically designed to indicate that the event
// occurred outside the mount point. Fortunately, as long as the
// target location can be referenced by a path beneath the mount
// point being used as the reference point for open_by_handle_at, a
// valid path will be returned. This means (e.g.) that a single
// volume mounted in multiple containers (even at different mount
// points) will still yield event notifications with paths relative
// to the mount point within the container performing the watch.

// Transmit the path.

// Events implements filesystem/watching.RecursiveWatcher.Events.
func (w *RecursiveWatcher) Events() <-chan string {
	_ = "STUB: not implemented"

	// Errors implements filesystem/watching.RecursiveWatcher.Errors.
	return nil
}

func (w *RecursiveWatcher) Errors() <-chan error {
	_ = "STUB: not implemented"

	// Terminate implements filesystem/watching.RecursiveWatcher.Terminate.
	return nil
}

func (w *RecursiveWatcher) Terminate() error {
	_ = "STUB: not implemented"
	// Write a termination error to the errors channel since we're going to
	// close the watch and we don't want a read error in the run loop to appear
	// to the consumer if it's simply due to termination.
	return nil
}

// Signal termination to run loop. The run loop can block in multiple ways
// and thus needs both watch closure and context cancellation to signal
// termination. The mount descriptor used for resolving paths is closed by
// the run loop Goroutine when it exits.

// Wait for the run loop to exit.

// Done.
