// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/compression/algorithm.proto

package compression

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Algorithm specifies a compression algorithm.
type Algorithm int32

const (
	// Algorithm_AlgorithmDefault represents an unspecified compression
	// algorithm. It should be converted to one of the following values based on
	// the desired default behavior.
	Algorithm_AlgorithmDefault Algorithm = 0
	// Algorithm_AlgorithmNone specifies that no compression should be used.
	Algorithm_AlgorithmNone Algorithm = 1
	// Algorithm_AlgorithmDeflate specifies that DEFLATE compression should be
	// used.
	Algorithm_AlgorithmDeflate Algorithm = 2
	// Algorithm_AlgorithmZstandard specifies that Zstandard compression should
	// be used.
	Algorithm_AlgorithmZstandard Algorithm = 3
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "AlgorithmDefault",
		1: "AlgorithmNone",
		2: "AlgorithmDeflate",
		3: "AlgorithmZstandard",
	}
	Algorithm_value = map[string]int32{
		"AlgorithmDefault":   0,
		"AlgorithmNone":      1,
		"AlgorithmDeflate":   2,
		"AlgorithmZstandard": 3,
	}
)

func (x Algorithm) Enum() *Algorithm { _ = "STUB: not implemented"; return nil }

func (x Algorithm) String() string { _ = "STUB: not implemented"; return "" }

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Algorithm) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_synchronization_compression_algorithm_proto protoreflect.FileDescriptor

const file_synchronization_compression_algorithm_proto_rawDesc = "" +
	"\n" +
	"+synchronization/compression/algorithm.proto\x12\vcompression*b\n" +
	"\tAlgorithm\x12\x14\n" +
	"\x10AlgorithmDefault\x10\x00\x12\x11\n" +
	"\rAlgorithmNone\x10\x01\x12\x14\n" +
	"\x10AlgorithmDeflate\x10\x02\x12\x16\n" +
	"\x12AlgorithmZstandard\x10\x03B?Z=github.com/mutagen-io/mutagen/pkg/synchronization/compressionb\x06proto3"

var (
	file_synchronization_compression_algorithm_proto_rawDescOnce sync.Once
	file_synchronization_compression_algorithm_proto_rawDescData []byte
)

func file_synchronization_compression_algorithm_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_compression_algorithm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_compression_algorithm_proto_goTypes = []any{
	(Algorithm)(0), // 0: compression.Algorithm
}
var file_synchronization_compression_algorithm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                                  { file_synchronization_compression_algorithm_proto_init() }
func file_synchronization_compression_algorithm_proto_init() { _ = "STUB: not implemented"; return }
