// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: forwarding/state.proto

package forwarding

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status encodes the status of a forwarding session.
type Status int32

const (
	// Status_Disconnected indicates that the session is disconnected.
	Status_Disconnected Status = 0
	// Status_ConnectingSource indicates that the session is in the process of
	// connecting to the source endpoint.
	Status_ConnectingSource Status = 1
	// Status_ConnectingDestination indicates that the session is in the process
	// of connecting to the destination endpoint.
	Status_ConnectingDestination Status = 2
	// Status_ForwardingConnections indicates that the session is connected and
	// currently forwarding connections.
	Status_ForwardingConnections Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Disconnected",
		1: "ConnectingSource",
		2: "ConnectingDestination",
		3: "ForwardingConnections",
	}
	Status_value = map[string]int32{
		"Disconnected":          0,
		"ConnectingSource":      1,
		"ConnectingDestination": 2,
		"ForwardingConnections": 3,
	}
)

func (x Status) Enum() *Status { _ = "STUB: not implemented"; return nil }

func (x Status) String() string { _ = "STUB: not implemented"; return "" }

func (Status) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Status) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Status) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// EndpointState encodes the current state of a forwarding endpoint. It is
// mutable within the context of the daemon, so it should be accessed and
// modified in a synchronized fashion. Outside of the daemon (e.g. when returned
// via the API), it should be considered immutable.
type EndpointState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connected indicates whether or not the controller is currently connected
	// to the endpoint.
	Connected     bool `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointState) Reset() { _ = "STUB: not implemented"; return }

func (x *EndpointState) String() string { _ = "STUB: not implemented"; return "" }

func (*EndpointState) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *EndpointState) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use EndpointState.ProtoReflect.Descriptor instead.
func (*EndpointState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *EndpointState) GetConnected() bool { _ = "STUB: not implemented"; return false }

// State encodes the current state of a forwarding session. It is mutable within
// the context of the daemon, so it should be accessed and modified in a
// synchronized fashion. Outside of the daemon (e.g. when returned via the API),
// it should be considered immutable.
type State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session is the session specification.
	Session *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Status is the status of the session.
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=forwarding.Status" json:"status,omitempty"`
	// LastError indicates the last error that occurred during forwarding.
	LastError string `protobuf:"bytes,3,opt,name=lastError,proto3" json:"lastError,omitempty"`
	// OpenConnections is the number of connections currently open and being
	// forwarded.
	OpenConnections uint64 `protobuf:"varint,4,opt,name=openConnections,proto3" json:"openConnections,omitempty"`
	// TotalConnections is the number of total connections that have been opened
	// and forwarded (including those that are currently open).
	TotalConnections uint64 `protobuf:"varint,5,opt,name=totalConnections,proto3" json:"totalConnections,omitempty"`
	// TotalOutboundData is the total amount of data (in bytes) that has been
	// transmitted from source to destination across all forwarded connections.
	TotalOutboundData uint64 `protobuf:"varint,6,opt,name=totalOutboundData,proto3" json:"totalOutboundData,omitempty"`
	// TotalInboundData is the total amount of data (in bytes) that has been
	// transmitted from destination to source across all forwarded connections.
	TotalInboundData uint64 `protobuf:"varint,7,opt,name=totalInboundData,proto3" json:"totalInboundData,omitempty"`
	// SourceState encodes the state of the source endpoint. It is always
	// non-nil.
	SourceState *EndpointState `protobuf:"bytes,8,opt,name=sourceState,proto3" json:"sourceState,omitempty"`
	// DestinationState encodes the state of the destination endpoint. It is
	// always non-nil.
	DestinationState *EndpointState `protobuf:"bytes,9,opt,name=destinationState,proto3" json:"destinationState,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *State) Reset() { _ = "STUB: not implemented"; return }

func (x *State) String() string { _ = "STUB: not implemented"; return "" }

func (*State) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *State) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *State) GetSession() *Session { _ = "STUB: not implemented"; return nil }

func (x *State) GetStatus() Status { _ = "STUB: not implemented"; return *new(Status) }

func (x *State) GetLastError() string { _ = "STUB: not implemented"; return "" }

func (x *State) GetOpenConnections() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *State) GetTotalConnections() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *State) GetTotalOutboundData() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *State) GetTotalInboundData() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *State) GetSourceState() *EndpointState { _ = "STUB: not implemented"; return nil }

func (x *State) GetDestinationState() *EndpointState { _ = "STUB: not implemented"; return nil }

var File_forwarding_state_proto protoreflect.FileDescriptor

const file_forwarding_state_proto_rawDesc = "" +
	"\n" +
	"\x16forwarding/state.proto\x12\n" +
	"forwarding\x1a\x18forwarding/session.proto\"-\n" +
	"\rEndpointState\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\"\xb4\x03\n" +
	"\x05State\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.forwarding.SessionR\asession\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.forwarding.StatusR\x06status\x12\x1c\n" +
	"\tlastError\x18\x03 \x01(\tR\tlastError\x12(\n" +
	"\x0fopenConnections\x18\x04 \x01(\x04R\x0fopenConnections\x12*\n" +
	"\x10totalConnections\x18\x05 \x01(\x04R\x10totalConnections\x12,\n" +
	"\x11totalOutboundData\x18\x06 \x01(\x04R\x11totalOutboundData\x12*\n" +
	"\x10totalInboundData\x18\a \x01(\x04R\x10totalInboundData\x12;\n" +
	"\vsourceState\x18\b \x01(\v2\x19.forwarding.EndpointStateR\vsourceState\x12E\n" +
	"\x10destinationState\x18\t \x01(\v2\x19.forwarding.EndpointStateR\x10destinationState*f\n" +
	"\x06Status\x12\x10\n" +
	"\fDisconnected\x10\x00\x12\x14\n" +
	"\x10ConnectingSource\x10\x01\x12\x19\n" +
	"\x15ConnectingDestination\x10\x02\x12\x19\n" +
	"\x15ForwardingConnections\x10\x03B.Z,github.com/mutagen-io/mutagen/pkg/forwardingb\x06proto3"

var (
	file_forwarding_state_proto_rawDescOnce sync.Once
	file_forwarding_state_proto_rawDescData []byte
)

func file_forwarding_state_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_forwarding_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_forwarding_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forwarding_state_proto_goTypes = []any{
	(Status)(0),           // 0: forwarding.Status
	(*EndpointState)(nil), // 1: forwarding.EndpointState
	(*State)(nil),         // 2: forwarding.State
	(*Session)(nil),       // 3: forwarding.Session
}
var file_forwarding_state_proto_depIdxs = []int32{
	3, // 0: forwarding.State.session:type_name -> forwarding.Session
	0, // 1: forwarding.State.status:type_name -> forwarding.Status
	1, // 2: forwarding.State.sourceState:type_name -> forwarding.EndpointState
	1, // 3: forwarding.State.destinationState:type_name -> forwarding.EndpointState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init()                             { file_forwarding_state_proto_init() }
func file_forwarding_state_proto_init() { _ = "STUB: not implemented"; return }
