// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: forwarding/version.proto

package forwarding

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Version specifies a session version, providing default behavior that can vary
// without affecting existing sessions.
type Version int32

const (
	// Invalid is the default session version and represents an unspecfied and
	// invalid version. It is used as a sanity check to ensure that version is
	// set for a session.
	Version_Invalid Version = 0
	// Version1 represents session version 1.
	Version_Version1 Version = 1
)

// Enum value maps for Version.
var (
	Version_name = map[int32]string{
		0: "Invalid",
		1: "Version1",
	}
	Version_value = map[string]int32{
		"Invalid":  0,
		"Version1": 1,
	}
)

func (x Version) Enum() *Version { _ = "STUB: not implemented"; return nil }

func (x Version) String() string { _ = "STUB: not implemented"; return "" }

func (Version) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Version) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Version) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Version.Descriptor instead.
func (Version) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_forwarding_version_proto protoreflect.FileDescriptor

const file_forwarding_version_proto_rawDesc = "" +
	"\n" +
	"\x18forwarding/version.proto\x12\n" +
	"forwarding*$\n" +
	"\aVersion\x12\v\n" +
	"\aInvalid\x10\x00\x12\f\n" +
	"\bVersion1\x10\x01B.Z,github.com/mutagen-io/mutagen/pkg/forwardingb\x06proto3"

var (
	file_forwarding_version_proto_rawDescOnce sync.Once
	file_forwarding_version_proto_rawDescData []byte
)

func file_forwarding_version_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_forwarding_version_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_forwarding_version_proto_goTypes = []any{
	(Version)(0), // 0: forwarding.Version
}
var file_forwarding_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                               { file_forwarding_version_proto_init() }
func file_forwarding_version_proto_init() { _ = "STUB: not implemented"; return }
