// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/rsync/receive.proto

package rsync

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReceiverState encodes that status of an rsync receiver. It should be
// considered immutable.
type ReceiverState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path is the path currently being received.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// ReceivedSize is the number of bytes that have been received for the
	// current path from both block and data operations.
	ReceivedSize uint64 `protobuf:"varint,2,opt,name=receivedSize,proto3" json:"receivedSize,omitempty"`
	// ExpectedSize is the number of bytes expected for the current path.
	ExpectedSize uint64 `protobuf:"varint,3,opt,name=expectedSize,proto3" json:"expectedSize,omitempty"`
	// ReceivedFiles is the number of files that have already been received.
	ReceivedFiles uint64 `protobuf:"varint,4,opt,name=receivedFiles,proto3" json:"receivedFiles,omitempty"`
	// ExpectedFiles is the total number of files expected.
	ExpectedFiles uint64 `protobuf:"varint,5,opt,name=expectedFiles,proto3" json:"expectedFiles,omitempty"`
	// TotalReceivedSize is the total number of bytes that have been received
	// for all files from both block and data operations.
	TotalReceivedSize uint64 `protobuf:"varint,6,opt,name=totalReceivedSize,proto3" json:"totalReceivedSize,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReceiverState) Reset() { _ = "STUB: not implemented"; return }

func (x *ReceiverState) String() string { _ = "STUB: not implemented"; return "" }

func (*ReceiverState) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ReceiverState) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ReceiverState.ProtoReflect.Descriptor instead.
func (*ReceiverState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ReceiverState) GetPath() string { _ = "STUB: not implemented"; return "" }

func (x *ReceiverState) GetReceivedSize() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *ReceiverState) GetExpectedSize() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *ReceiverState) GetReceivedFiles() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *ReceiverState) GetExpectedFiles() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *ReceiverState) GetTotalReceivedSize() uint64 { _ = "STUB: not implemented"; return 0 }

var File_synchronization_rsync_receive_proto protoreflect.FileDescriptor

const file_synchronization_rsync_receive_proto_rawDesc = "" +
	"\n" +
	"#synchronization/rsync/receive.proto\x12\x05rsync\"\xe5\x01\n" +
	"\rReceiverState\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\"\n" +
	"\freceivedSize\x18\x02 \x01(\x04R\freceivedSize\x12\"\n" +
	"\fexpectedSize\x18\x03 \x01(\x04R\fexpectedSize\x12$\n" +
	"\rreceivedFiles\x18\x04 \x01(\x04R\rreceivedFiles\x12$\n" +
	"\rexpectedFiles\x18\x05 \x01(\x04R\rexpectedFiles\x12,\n" +
	"\x11totalReceivedSize\x18\x06 \x01(\x04R\x11totalReceivedSizeB9Z7github.com/mutagen-io/mutagen/pkg/synchronization/rsyncb\x06proto3"

var (
	file_synchronization_rsync_receive_proto_rawDescOnce sync.Once
	file_synchronization_rsync_receive_proto_rawDescData []byte
)

func file_synchronization_rsync_receive_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_rsync_receive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_synchronization_rsync_receive_proto_goTypes = []any{
	(*ReceiverState)(nil), // 0: rsync.ReceiverState
}
var file_synchronization_rsync_receive_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                          { file_synchronization_rsync_receive_proto_init() }
func file_synchronization_rsync_receive_proto_init() { _ = "STUB: not implemented"; return }
