// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/rsync/transmission.proto

package rsync

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transmission represents a single message in a transmission stream. As a
// Protocol Buffers message type, its internals are inherently public, but it
// should otherwise be treated as an opaque type with a private implementation.
type Transmission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ExpectedSize sets the expected size for the current incoming file. It is
	// only set alongside the first operation in a file's transmission stream.
	// If it zero, then the file's size should be treated as unknown, because a
	// file of zero size will receive an immediate "done" transmission and would
	// not be indicated as having zero size.
	ExpectedSize uint64 `protobuf:"varint,1,opt,name=expectedSize,proto3" json:"expectedSize,omitempty"`
	// Operation is the next operation in the transmission stream for the
	// current file.
	Operation *Operation `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// Done indicates that the transmission stream for the current file is
	// finished. If Done is true, then there will be no operation set, but there
	// may be an error set.
	Done bool `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	// Error indicates that a non-terminal error has occurred. It can only be
	// present if Done is true.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transmission) Reset() { _ = "STUB: not implemented"; return }

func (x *Transmission) String() string { _ = "STUB: not implemented"; return "" }

func (*Transmission) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Transmission) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Transmission.ProtoReflect.Descriptor instead.
func (*Transmission) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Transmission) GetExpectedSize() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *Transmission) GetOperation() *Operation { _ = "STUB: not implemented"; return nil }

func (x *Transmission) GetDone() bool { _ = "STUB: not implemented"; return false }

func (x *Transmission) GetError() string { _ = "STUB: not implemented"; return "" }

var File_synchronization_rsync_transmission_proto protoreflect.FileDescriptor

const file_synchronization_rsync_transmission_proto_rawDesc = "" +
	"\n" +
	"(synchronization/rsync/transmission.proto\x12\x05rsync\x1a\"synchronization/rsync/engine.proto\"\x8c\x01\n" +
	"\fTransmission\x12\"\n" +
	"\fexpectedSize\x18\x01 \x01(\x04R\fexpectedSize\x12.\n" +
	"\toperation\x18\x02 \x01(\v2\x10.rsync.OperationR\toperation\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB9Z7github.com/mutagen-io/mutagen/pkg/synchronization/rsyncb\x06proto3"

var (
	file_synchronization_rsync_transmission_proto_rawDescOnce sync.Once
	file_synchronization_rsync_transmission_proto_rawDescData []byte
)

func file_synchronization_rsync_transmission_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_rsync_transmission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_synchronization_rsync_transmission_proto_goTypes = []any{
	(*Transmission)(nil), // 0: rsync.Transmission
	(*Operation)(nil),    // 1: rsync.Operation
}
var file_synchronization_rsync_transmission_proto_depIdxs = []int32{
	1, // 0: rsync.Transmission.operation:type_name -> rsync.Operation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init()                                               { file_synchronization_rsync_transmission_proto_init() }
func file_synchronization_rsync_transmission_proto_init() { _ = "STUB: not implemented"; return }
