// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: filesystem/behavior/probe_mode.proto

package behavior

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProbeMode specifies the mode for filesystem probing.
type ProbeMode int32

const (
	// ProbeMode_ProbeModeDefault represents an unspecified probe mode. It
	// should be converted to one of the following values based on the desired
	// default behavior.
	ProbeMode_ProbeModeDefault ProbeMode = 0
	// ProbeMode_ProbeModeProbe specifies that filesystem behavior should be
	// determined using temporary files or, if possible, a "fast-path" mechanism
	// (such as filesystem format detection) that provides quick but certain
	// determination of filesystem behavior.
	ProbeMode_ProbeModeProbe ProbeMode = 1
	// ProbeMode_ProbeModeAssume specifies that filesystem behavior should be
	// assumed based on the underlying platform. This is not as accurate as
	// ProbeMode_ProbeModeProbe.
	ProbeMode_ProbeModeAssume ProbeMode = 2
)

// Enum value maps for ProbeMode.
var (
	ProbeMode_name = map[int32]string{
		0: "ProbeModeDefault",
		1: "ProbeModeProbe",
		2: "ProbeModeAssume",
	}
	ProbeMode_value = map[string]int32{
		"ProbeModeDefault": 0,
		"ProbeModeProbe":   1,
		"ProbeModeAssume":  2,
	}
)

func (x ProbeMode) Enum() *ProbeMode { _ = "STUB: not implemented"; return nil }

func (x ProbeMode) String() string { _ = "STUB: not implemented"; return "" }

func (ProbeMode) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (ProbeMode) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x ProbeMode) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use ProbeMode.Descriptor instead.
func (ProbeMode) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_filesystem_behavior_probe_mode_proto protoreflect.FileDescriptor

const file_filesystem_behavior_probe_mode_proto_rawDesc = "" +
	"\n" +
	"$filesystem/behavior/probe_mode.proto\x12\bbehavior*J\n" +
	"\tProbeMode\x12\x14\n" +
	"\x10ProbeModeDefault\x10\x00\x12\x12\n" +
	"\x0eProbeModeProbe\x10\x01\x12\x13\n" +
	"\x0fProbeModeAssume\x10\x02B7Z5github.com/mutagen-io/mutagen/pkg/filesystem/behaviorb\x06proto3"

var (
	file_filesystem_behavior_probe_mode_proto_rawDescOnce sync.Once
	file_filesystem_behavior_probe_mode_proto_rawDescData []byte
)

func file_filesystem_behavior_probe_mode_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_filesystem_behavior_probe_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_filesystem_behavior_probe_mode_proto_goTypes = []any{
	(ProbeMode)(0), // 0: behavior.ProbeMode
}
var file_filesystem_behavior_probe_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                           { file_filesystem_behavior_probe_mode_proto_init() }
func file_filesystem_behavior_probe_mode_proto_init() { _ = "STUB: not implemented"; return }
