// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/configuration.proto

package synchronization

import (
	sync "sync"

	behavior "github.com/mutagen-io/mutagen/pkg/filesystem/behavior"
	compression "github.com/mutagen-io/mutagen/pkg/synchronization/compression"
	core "github.com/mutagen-io/mutagen/pkg/synchronization/core"
	ignore "github.com/mutagen-io/mutagen/pkg/synchronization/core/ignore"
	hashing "github.com/mutagen-io/mutagen/pkg/synchronization/hashing"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration encodes session configuration parameters. It is used for create
// commands to specify configuration options, for loading global configuration
// options, and for storing a merged configuration inside sessions. It should be
// considered immutable.
type Configuration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SynchronizationMode specifies the synchronization mode that should be
	// used in synchronization.
	SynchronizationMode core.SynchronizationMode `protobuf:"varint,11,opt,name=synchronizationMode,proto3,enum=core.SynchronizationMode" json:"synchronizationMode,omitempty"`
	// HashingAlgorithm specifies the content hashing algorithm used to track
	// content and perform differential transfers.
	HashingAlgorithm hashing.Algorithm `protobuf:"varint,17,opt,name=hashingAlgorithm,proto3,enum=hashing.Algorithm" json:"hashingAlgorithm,omitempty"`
	// MaximumEntryCount specifies the maximum number of filesystem entries that
	// endpoints will tolerate managing. A zero value indicates no limit.
	MaximumEntryCount uint64 `protobuf:"varint,12,opt,name=maximumEntryCount,proto3" json:"maximumEntryCount,omitempty"`
	// MaximumStagingFileSize is the maximum (individual) file size that
	// endpoints will stage. A zero value indicates no limit.
	MaximumStagingFileSize uint64 `protobuf:"varint,13,opt,name=maximumStagingFileSize,proto3" json:"maximumStagingFileSize,omitempty"`
	// ProbeMode specifies the filesystem probing mode.
	ProbeMode behavior.ProbeMode `protobuf:"varint,14,opt,name=probeMode,proto3,enum=behavior.ProbeMode" json:"probeMode,omitempty"`
	// ScanMode specifies the synchronization root scanning mode.
	ScanMode ScanMode `protobuf:"varint,15,opt,name=scanMode,proto3,enum=synchronization.ScanMode" json:"scanMode,omitempty"`
	// StageMode specifies the file staging mode.
	StageMode StageMode `protobuf:"varint,16,opt,name=stageMode,proto3,enum=synchronization.StageMode" json:"stageMode,omitempty"`
	// SymbolicLinkMode specifies the symbolic link mode.
	SymbolicLinkMode core.SymbolicLinkMode `protobuf:"varint,1,opt,name=symbolicLinkMode,proto3,enum=core.SymbolicLinkMode" json:"symbolicLinkMode,omitempty"`
	// WatchMode specifies the filesystem watching mode.
	WatchMode WatchMode `protobuf:"varint,21,opt,name=watchMode,proto3,enum=synchronization.WatchMode" json:"watchMode,omitempty"`
	// WatchPollingInterval specifies the interval (in seconds) for poll-based
	// file monitoring. A value of 0 specifies that the default interval should
	// be used.
	WatchPollingInterval uint32 `protobuf:"varint,22,opt,name=watchPollingInterval,proto3" json:"watchPollingInterval,omitempty"`
	// IgnoreSyntax specifies the syntax and semantics to use for ignores.
	// NOTE: This field is out of order due to the historical order in which it
	// was added.
	IgnoreSyntax ignore.Syntax `protobuf:"varint,34,opt,name=ignoreSyntax,proto3,enum=ignore.Syntax" json:"ignoreSyntax,omitempty"`
	// DefaultIgnores specifies the ignore patterns brought in from the global
	// configuration.
	// DEPRECATED: This field is no longer used when loading from global
	// configuration. Instead, ignores provided by global configuration are
	// simply merged into the ignore list of the main configuration. However,
	// older sessions still use this field.
	DefaultIgnores []string `protobuf:"bytes,31,rep,name=defaultIgnores,proto3" json:"defaultIgnores,omitempty"`
	// Ignores specifies the ignore patterns brought in from the create request.
	Ignores []string `protobuf:"bytes,32,rep,name=ignores,proto3" json:"ignores,omitempty"`
	// IgnoreVCSMode specifies the VCS ignore mode that should be used in
	// synchronization.
	IgnoreVCSMode ignore.IgnoreVCSMode `protobuf:"varint,33,opt,name=ignoreVCSMode,proto3,enum=ignore.IgnoreVCSMode" json:"ignoreVCSMode,omitempty"`
	// PermissionsMode species the manner in which permissions should be
	// propagated between endpoints.
	PermissionsMode core.PermissionsMode `protobuf:"varint,61,opt,name=permissionsMode,proto3,enum=core.PermissionsMode" json:"permissionsMode,omitempty"`
	// DefaultFileMode specifies the default permission mode to use for new
	// files in "portable" permission propagation mode.
	DefaultFileMode uint32 `protobuf:"varint,63,opt,name=defaultFileMode,proto3" json:"defaultFileMode,omitempty"`
	// DefaultDirectoryMode specifies the default permission mode to use for new
	// files in "portable" permission propagation mode.
	DefaultDirectoryMode uint32 `protobuf:"varint,64,opt,name=defaultDirectoryMode,proto3" json:"defaultDirectoryMode,omitempty"`
	// DefaultOwner specifies the default owner identifier to use when setting
	// ownership of new files and directories in "portable" permission
	// propagation mode.
	DefaultOwner string `protobuf:"bytes,65,opt,name=defaultOwner,proto3" json:"defaultOwner,omitempty"`
	// DefaultGroup specifies the default group identifier to use when setting
	// ownership of new files and directories in "portable" permission
	// propagation mode.
	DefaultGroup string `protobuf:"bytes,66,opt,name=defaultGroup,proto3" json:"defaultGroup,omitempty"`
	// CompressionAlgorithm specifies the compression algorithm to use when
	// communicating with the endpoint. This only applies to remote endpoints.
	CompressionAlgorithm compression.Algorithm `protobuf:"varint,81,opt,name=compressionAlgorithm,proto3,enum=compression.Algorithm" json:"compressionAlgorithm,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Configuration) Reset() { _ = "STUB: not implemented"; return }

func (x *Configuration) String() string { _ = "STUB: not implemented"; return "" }

func (*Configuration) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Configuration) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Configuration) GetSynchronizationMode() core.SynchronizationMode {
	_ = "STUB: not implemented"
	return *new(core.SynchronizationMode)
}

func (x *Configuration) GetHashingAlgorithm() hashing.Algorithm {
	_ = "STUB: not implemented"
	return *new(hashing.Algorithm)
}

func (x *Configuration) GetMaximumEntryCount() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *Configuration) GetMaximumStagingFileSize() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *Configuration) GetProbeMode() behavior.ProbeMode {
	_ = "STUB: not implemented"
	return *new(behavior.ProbeMode)
}

func (x *Configuration) GetScanMode() ScanMode { _ = "STUB: not implemented"; return *new(ScanMode) }

func (x *Configuration) GetStageMode() StageMode { _ = "STUB: not implemented"; return *new(StageMode) }

func (x *Configuration) GetSymbolicLinkMode() core.SymbolicLinkMode {
	_ = "STUB: not implemented"
	return *new(core.SymbolicLinkMode)
}

func (x *Configuration) GetWatchMode() WatchMode { _ = "STUB: not implemented"; return *new(WatchMode) }

func (x *Configuration) GetWatchPollingInterval() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Configuration) GetIgnoreSyntax() ignore.Syntax {
	_ = "STUB: not implemented"
	return *new(ignore.Syntax)
}

func (x *Configuration) GetDefaultIgnores() []string { _ = "STUB: not implemented"; return nil }

func (x *Configuration) GetIgnores() []string { _ = "STUB: not implemented"; return nil }

func (x *Configuration) GetIgnoreVCSMode() ignore.IgnoreVCSMode {
	_ = "STUB: not implemented"
	return *new(ignore.IgnoreVCSMode)
}

func (x *Configuration) GetPermissionsMode() core.PermissionsMode {
	_ = "STUB: not implemented"
	return *new(core.PermissionsMode)
}

func (x *Configuration) GetDefaultFileMode() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Configuration) GetDefaultDirectoryMode() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Configuration) GetDefaultOwner() string { _ = "STUB: not implemented"; return "" }

func (x *Configuration) GetDefaultGroup() string { _ = "STUB: not implemented"; return "" }

func (x *Configuration) GetCompressionAlgorithm() compression.Algorithm {
	_ = "STUB: not implemented"
	return *new(compression.Algorithm)
}

var File_synchronization_configuration_proto protoreflect.FileDescriptor

const file_synchronization_configuration_proto_rawDesc = "" +
	"\n" +
	"#synchronization/configuration.proto\x12\x0fsynchronization\x1a$filesystem/behavior/probe_mode.proto\x1a\x1fsynchronization/scan_mode.proto\x1a synchronization/stage_mode.proto\x1a synchronization/watch_mode.proto\x1a+synchronization/compression/algorithm.proto\x1a\x1fsynchronization/core/mode.proto\x1a+synchronization/core/permissions_mode.proto\x1a-synchronization/core/symbolic_link_mode.proto\x1a(synchronization/core/ignore/syntax.proto\x1a1synchronization/core/ignore/ignore_vcs_mode.proto\x1a'synchronization/hashing/algorithm.proto\"\xbe\b\n" +
	"\rConfiguration\x12K\n" +
	"\x13synchronizationMode\x18\v \x01(\x0e2\x19.core.SynchronizationModeR\x13synchronizationMode\x12>\n" +
	"\x10hashingAlgorithm\x18\x11 \x01(\x0e2\x12.hashing.AlgorithmR\x10hashingAlgorithm\x12,\n" +
	"\x11maximumEntryCount\x18\f \x01(\x04R\x11maximumEntryCount\x126\n" +
	"\x16maximumStagingFileSize\x18\r \x01(\x04R\x16maximumStagingFileSize\x121\n" +
	"\tprobeMode\x18\x0e \x01(\x0e2\x13.behavior.ProbeModeR\tprobeMode\x125\n" +
	"\bscanMode\x18\x0f \x01(\x0e2\x19.synchronization.ScanModeR\bscanMode\x128\n" +
	"\tstageMode\x18\x10 \x01(\x0e2\x1a.synchronization.StageModeR\tstageMode\x12B\n" +
	"\x10symbolicLinkMode\x18\x01 \x01(\x0e2\x16.core.SymbolicLinkModeR\x10symbolicLinkMode\x128\n" +
	"\twatchMode\x18\x15 \x01(\x0e2\x1a.synchronization.WatchModeR\twatchMode\x122\n" +
	"\x14watchPollingInterval\x18\x16 \x01(\rR\x14watchPollingInterval\x122\n" +
	"\fignoreSyntax\x18\" \x01(\x0e2\x0e.ignore.SyntaxR\fignoreSyntax\x12&\n" +
	"\x0edefaultIgnores\x18\x1f \x03(\tR\x0edefaultIgnores\x12\x18\n" +
	"\aignores\x18  \x03(\tR\aignores\x12;\n" +
	"\rignoreVCSMode\x18! \x01(\x0e2\x15.ignore.IgnoreVCSModeR\rignoreVCSMode\x12?\n" +
	"\x0fpermissionsMode\x18= \x01(\x0e2\x15.core.PermissionsModeR\x0fpermissionsMode\x12(\n" +
	"\x0fdefaultFileMode\x18? \x01(\rR\x0fdefaultFileMode\x122\n" +
	"\x14defaultDirectoryMode\x18@ \x01(\rR\x14defaultDirectoryMode\x12\"\n" +
	"\fdefaultOwner\x18A \x01(\tR\fdefaultOwner\x12\"\n" +
	"\fdefaultGroup\x18B \x01(\tR\fdefaultGroup\x12J\n" +
	"\x14compressionAlgorithm\x18Q \x01(\x0e2\x16.compression.AlgorithmR\x14compressionAlgorithmB3Z1github.com/mutagen-io/mutagen/pkg/synchronizationb\x06proto3"

var (
	file_synchronization_configuration_proto_rawDescOnce sync.Once
	file_synchronization_configuration_proto_rawDescData []byte
)

func file_synchronization_configuration_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_synchronization_configuration_proto_goTypes = []any{
	(*Configuration)(nil),         // 0: synchronization.Configuration
	(core.SynchronizationMode)(0), // 1: core.SynchronizationMode
	(hashing.Algorithm)(0),        // 2: hashing.Algorithm
	(behavior.ProbeMode)(0),       // 3: behavior.ProbeMode
	(ScanMode)(0),                 // 4: synchronization.ScanMode
	(StageMode)(0),                // 5: synchronization.StageMode
	(core.SymbolicLinkMode)(0),    // 6: core.SymbolicLinkMode
	(WatchMode)(0),                // 7: synchronization.WatchMode
	(ignore.Syntax)(0),            // 8: ignore.Syntax
	(ignore.IgnoreVCSMode)(0),     // 9: ignore.IgnoreVCSMode
	(core.PermissionsMode)(0),     // 10: core.PermissionsMode
	(compression.Algorithm)(0),    // 11: compression.Algorithm
}
var file_synchronization_configuration_proto_depIdxs = []int32{
	1,  // 0: synchronization.Configuration.synchronizationMode:type_name -> core.SynchronizationMode
	2,  // 1: synchronization.Configuration.hashingAlgorithm:type_name -> hashing.Algorithm
	3,  // 2: synchronization.Configuration.probeMode:type_name -> behavior.ProbeMode
	4,  // 3: synchronization.Configuration.scanMode:type_name -> synchronization.ScanMode
	5,  // 4: synchronization.Configuration.stageMode:type_name -> synchronization.StageMode
	6,  // 5: synchronization.Configuration.symbolicLinkMode:type_name -> core.SymbolicLinkMode
	7,  // 6: synchronization.Configuration.watchMode:type_name -> synchronization.WatchMode
	8,  // 7: synchronization.Configuration.ignoreSyntax:type_name -> ignore.Syntax
	9,  // 8: synchronization.Configuration.ignoreVCSMode:type_name -> ignore.IgnoreVCSMode
	10, // 9: synchronization.Configuration.permissionsMode:type_name -> core.PermissionsMode
	11, // 10: synchronization.Configuration.compressionAlgorithm:type_name -> compression.Algorithm
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init()                                          { file_synchronization_configuration_proto_init() }
func file_synchronization_configuration_proto_init() { _ = "STUB: not implemented"; return }
