// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/scan_mode.proto

package synchronization

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScanMode specifies the mode for synchronization root scanning.
type ScanMode int32

const (
	// ScanMode_ScanModeDefault represents an unspecified scan mode. It should
	// be converted to one of the following values based on the desired default
	// behavior.
	ScanMode_ScanModeDefault ScanMode = 0
	// ScanMode_ScanModeFull specifies that full scans should be performed on
	// each synchronization cycle.
	ScanMode_ScanModeFull ScanMode = 1
	// ScanMode_ScanModeAccelerated specifies that scans should attempt to use
	// watch-based acceleration.
	ScanMode_ScanModeAccelerated ScanMode = 2
)

// Enum value maps for ScanMode.
var (
	ScanMode_name = map[int32]string{
		0: "ScanModeDefault",
		1: "ScanModeFull",
		2: "ScanModeAccelerated",
	}
	ScanMode_value = map[string]int32{
		"ScanModeDefault":     0,
		"ScanModeFull":        1,
		"ScanModeAccelerated": 2,
	}
)

func (x ScanMode) Enum() *ScanMode { _ = "STUB: not implemented"; return nil }

func (x ScanMode) String() string { _ = "STUB: not implemented"; return "" }

func (ScanMode) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (ScanMode) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x ScanMode) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use ScanMode.Descriptor instead.
func (ScanMode) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_synchronization_scan_mode_proto protoreflect.FileDescriptor

const file_synchronization_scan_mode_proto_rawDesc = "" +
	"\n" +
	"\x1fsynchronization/scan_mode.proto\x12\x0fsynchronization*J\n" +
	"\bScanMode\x12\x13\n" +
	"\x0fScanModeDefault\x10\x00\x12\x10\n" +
	"\fScanModeFull\x10\x01\x12\x17\n" +
	"\x13ScanModeAccelerated\x10\x02B3Z1github.com/mutagen-io/mutagen/pkg/synchronizationb\x06proto3"

var (
	file_synchronization_scan_mode_proto_rawDescOnce sync.Once
	file_synchronization_scan_mode_proto_rawDescData []byte
)

func file_synchronization_scan_mode_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_scan_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_scan_mode_proto_goTypes = []any{
	(ScanMode)(0), // 0: synchronization.ScanMode
}
var file_synchronization_scan_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                      { file_synchronization_scan_mode_proto_init() }
func file_synchronization_scan_mode_proto_init() { _ = "STUB: not implemented"; return }
