// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/stage_mode.proto

package synchronization

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StageMode specifies the mode for file staging.
type StageMode int32

const (
	// StageMode_StageModeDefault represents an unspecified staging mode. It
	// should be converted to one of the following values based on the desired
	// default behavior.
	StageMode_StageModeDefault StageMode = 0
	// StageMode_StageModeMutagen specifies that files should be staged in the
	// Mutagen data directory.
	StageMode_StageModeMutagen StageMode = 1
	// StageMode_StageModeNeighboring specifies that files should be staged in a
	// directory which neighbors the synchronization root.
	StageMode_StageModeNeighboring StageMode = 2
	// StageMode_StageModeInternal specified that files should be staged in a
	// directory contained within a synchronization root. This mode will only
	// function if the synchronization root already exists.
	StageMode_StageModeInternal StageMode = 3
)

// Enum value maps for StageMode.
var (
	StageMode_name = map[int32]string{
		0: "StageModeDefault",
		1: "StageModeMutagen",
		2: "StageModeNeighboring",
		3: "StageModeInternal",
	}
	StageMode_value = map[string]int32{
		"StageModeDefault":     0,
		"StageModeMutagen":     1,
		"StageModeNeighboring": 2,
		"StageModeInternal":    3,
	}
)

func (x StageMode) Enum() *StageMode { _ = "STUB: not implemented"; return nil }

func (x StageMode) String() string { _ = "STUB: not implemented"; return "" }

func (StageMode) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (StageMode) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x StageMode) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use StageMode.Descriptor instead.
func (StageMode) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_synchronization_stage_mode_proto protoreflect.FileDescriptor

const file_synchronization_stage_mode_proto_rawDesc = "" +
	"\n" +
	" synchronization/stage_mode.proto\x12\x0fsynchronization*h\n" +
	"\tStageMode\x12\x14\n" +
	"\x10StageModeDefault\x10\x00\x12\x14\n" +
	"\x10StageModeMutagen\x10\x01\x12\x18\n" +
	"\x14StageModeNeighboring\x10\x02\x12\x15\n" +
	"\x11StageModeInternal\x10\x03B3Z1github.com/mutagen-io/mutagen/pkg/synchronizationb\x06proto3"

var (
	file_synchronization_stage_mode_proto_rawDescOnce sync.Once
	file_synchronization_stage_mode_proto_rawDescData []byte
)

func file_synchronization_stage_mode_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_stage_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_stage_mode_proto_goTypes = []any{
	(StageMode)(0), // 0: synchronization.StageMode
}
var file_synchronization_stage_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                       { file_synchronization_stage_mode_proto_init() }
func file_synchronization_stage_mode_proto_init() { _ = "STUB: not implemented"; return }
