// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/state.proto

package synchronization

import (
	sync "sync"

	core "github.com/mutagen-io/mutagen/pkg/synchronization/core"
	rsync "github.com/mutagen-io/mutagen/pkg/synchronization/rsync"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status encodes the status of a synchronization session.
type Status int32

const (
	// Status_Disconnected indicates that the session is unpaused but not
	// currently connected or connecting to either endpoint.
	Status_Disconnected Status = 0
	// Status_HaltedOnRootEmptied indicates that the session is halted due to
	// the root emptying safety check.
	Status_HaltedOnRootEmptied Status = 1
	// Status_HaltedOnRootDeletion indicates that the session is halted due to
	// the root deletion safety check.
	Status_HaltedOnRootDeletion Status = 2
	// Status_HaltedOnRootTypeChange indicates that the session is halted due to
	// the root type change safety check.
	Status_HaltedOnRootTypeChange Status = 3
	// Status_ConnectingAlpha indicates that the session is attempting to
	// connect to the alpha endpoint.
	Status_ConnectingAlpha Status = 4
	// Status_ConnectingBeta indicates that the session is attempting to connect
	// to the beta endpoint.
	Status_ConnectingBeta Status = 5
	// Status_Watching indicates that the session is watching for filesystem
	// changes.
	Status_Watching Status = 6
	// Status_Scanning indicates that the session is scanning the filesystem on
	// each endpoint.
	Status_Scanning Status = 7
	// Status_WaitingForRescan indicates that the session is waiting to retry
	// scanning after an error during the previous scanning operation.
	Status_WaitingForRescan Status = 8
	// Status_Reconciling indicates that the session is performing
	// reconciliation.
	Status_Reconciling Status = 9
	// Status_StagingAlpha indicates that the session is staging files on alpha.
	Status_StagingAlpha Status = 10
	// Status_StagingBeta indicates that the session is staging files on beta.
	Status_StagingBeta Status = 11
	// Status_Transitioning indicates that the session is performing transition
	// operations on each endpoint.
	Status_Transitioning Status = 12
	// Status_Saving indicates that the session is recording synchronization
	// history to disk.
	Status_Saving Status = 13
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0:  "Disconnected",
		1:  "HaltedOnRootEmptied",
		2:  "HaltedOnRootDeletion",
		3:  "HaltedOnRootTypeChange",
		4:  "ConnectingAlpha",
		5:  "ConnectingBeta",
		6:  "Watching",
		7:  "Scanning",
		8:  "WaitingForRescan",
		9:  "Reconciling",
		10: "StagingAlpha",
		11: "StagingBeta",
		12: "Transitioning",
		13: "Saving",
	}
	Status_value = map[string]int32{
		"Disconnected":           0,
		"HaltedOnRootEmptied":    1,
		"HaltedOnRootDeletion":   2,
		"HaltedOnRootTypeChange": 3,
		"ConnectingAlpha":        4,
		"ConnectingBeta":         5,
		"Watching":               6,
		"Scanning":               7,
		"WaitingForRescan":       8,
		"Reconciling":            9,
		"StagingAlpha":           10,
		"StagingBeta":            11,
		"Transitioning":          12,
		"Saving":                 13,
	}
)

func (x Status) Enum() *Status { _ = "STUB: not implemented"; return nil }

func (x Status) String() string { _ = "STUB: not implemented"; return "" }

func (Status) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Status) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Status) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// EndpointState encodes the current state of a synchronization endpoint. It is
// mutable within the context of the daemon, so it should be accessed and
// modified in a synchronized fashion. Outside of the daemon (e.g. when returned
// via the API), it should be considered immutable.
type EndpointState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connected indicates whether or not the controller is currently connected
	// to the endpoint.
	Connected bool `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	// Scanned indicates whether or not at least one scan has been performed on
	// the endpoint.
	Scanned bool `protobuf:"varint,2,opt,name=scanned,proto3" json:"scanned,omitempty"`
	// Directories is the number of synchronizable directory entries contained
	// in the last snapshot from the endpoint.
	Directories uint64 `protobuf:"varint,3,opt,name=directories,proto3" json:"directories,omitempty"`
	// Files is the number of synchronizable file entries contained in the last
	// snapshot from the endpoint.
	Files uint64 `protobuf:"varint,4,opt,name=files,proto3" json:"files,omitempty"`
	// SymbolicLinks is the number of synchronizable symbolic link entries
	// contained in the last snapshot from the endpoint.
	SymbolicLinks uint64 `protobuf:"varint,5,opt,name=symbolicLinks,proto3" json:"symbolicLinks,omitempty"`
	// TotalFileSize is the total size of all synchronizable files referenced by
	// the last snapshot from the endpoint.
	TotalFileSize uint64 `protobuf:"varint,6,opt,name=totalFileSize,proto3" json:"totalFileSize,omitempty"`
	// ScanProblems is the list of non-terminal problems encountered during the
	// last scanning operation on the endpoint. This list may be a truncated
	// version of the full list if too many problems are encountered to report
	// via the API, in which case ExcludedScanProblems will be non-zero.
	ScanProblems []*core.Problem `protobuf:"bytes,7,rep,name=scanProblems,proto3" json:"scanProblems,omitempty"`
	// ExcludedScanProblems is the number of problems that have been excluded
	// from ScanProblems due to truncation. This value can be non-zero only if
	// ScanProblems is non-empty.
	ExcludedScanProblems uint64 `protobuf:"varint,8,opt,name=excludedScanProblems,proto3" json:"excludedScanProblems,omitempty"`
	// TransitionProblems is the list of non-terminal problems encountered
	// during the last transition operation on the endpoint. This list may be a
	// truncated version of the full list if too many problems are encountered
	// to report via the API, in which case ExcludedTransitionProblems will be
	// non-zero.
	TransitionProblems []*core.Problem `protobuf:"bytes,9,rep,name=transitionProblems,proto3" json:"transitionProblems,omitempty"`
	// ExcludedTransitionProblems is the number of problems that have been
	// excluded from TransitionProblems due to truncation. This value can be
	// non-zero only if TransitionProblems is non-empty.
	ExcludedTransitionProblems uint64 `protobuf:"varint,10,opt,name=excludedTransitionProblems,proto3" json:"excludedTransitionProblems,omitempty"`
	// StagingProgress is the rsync staging progress. It is non-nil if and only
	// if the endpoint is currently staging files.
	StagingProgress *rsync.ReceiverState `protobuf:"bytes,11,opt,name=stagingProgress,proto3" json:"stagingProgress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EndpointState) Reset() { _ = "STUB: not implemented"; return }

func (x *EndpointState) String() string { _ = "STUB: not implemented"; return "" }

func (*EndpointState) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *EndpointState) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use EndpointState.ProtoReflect.Descriptor instead.
func (*EndpointState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *EndpointState) GetConnected() bool { _ = "STUB: not implemented"; return false }

func (x *EndpointState) GetScanned() bool { _ = "STUB: not implemented"; return false }

func (x *EndpointState) GetDirectories() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *EndpointState) GetFiles() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *EndpointState) GetSymbolicLinks() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *EndpointState) GetTotalFileSize() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *EndpointState) GetScanProblems() []*core.Problem { _ = "STUB: not implemented"; return nil }

func (x *EndpointState) GetExcludedScanProblems() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *EndpointState) GetTransitionProblems() []*core.Problem {
	_ = "STUB: not implemented"
	return nil
}

func (x *EndpointState) GetExcludedTransitionProblems() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *EndpointState) GetStagingProgress() *rsync.ReceiverState {
	_ = "STUB: not implemented"
	return nil
}

// State encodes the current state of a synchronization session. It is mutable
// within the context of the daemon, so it should be accessed and modified in a
// synchronized fashion. Outside of the daemon (e.g. when returned via the API),
// it should be considered immutable.
type State struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session is the session metadata. If the session is paused, then the
	// remainder of the fields in this structure should be ignored.
	Session *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Status is the session status.
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=synchronization.Status" json:"status,omitempty"`
	// LastError is the last error to occur during synchronization. It is
	// cleared after a successful synchronization cycle.
	LastError string `protobuf:"bytes,3,opt,name=lastError,proto3" json:"lastError,omitempty"`
	// SuccessfulCycles is the number of successful synchronization cycles to
	// occur since successfully connecting to the endpoints.
	SuccessfulCycles uint64 `protobuf:"varint,4,opt,name=successfulCycles,proto3" json:"successfulCycles,omitempty"`
	// Conflicts are the content conflicts identified during reconciliation.
	// This list may be a truncated version of the full list if too many
	// conflicts are encountered to report via the API, in which case
	// ExcludedConflicts will be non-zero.
	Conflicts []*core.Conflict `protobuf:"bytes,5,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	// ExcludedConflicts is the number of conflicts that have been excluded from
	// Conflicts due to truncation. This value can be non-zero only if conflicts
	// is non-empty.
	ExcludedConflicts uint64 `protobuf:"varint,6,opt,name=excludedConflicts,proto3" json:"excludedConflicts,omitempty"`
	// AlphaState encodes the state of the alpha endpoint. It is always non-nil.
	AlphaState *EndpointState `protobuf:"bytes,7,opt,name=alphaState,proto3" json:"alphaState,omitempty"`
	// BetaState encodes the state of the beta endpoint. It is always non-nil.
	BetaState     *EndpointState `protobuf:"bytes,8,opt,name=betaState,proto3" json:"betaState,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() { _ = "STUB: not implemented"; return }

func (x *State) String() string { _ = "STUB: not implemented"; return "" }

func (*State) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *State) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *State) GetSession() *Session { _ = "STUB: not implemented"; return nil }

func (x *State) GetStatus() Status { _ = "STUB: not implemented"; return *new(Status) }

func (x *State) GetLastError() string { _ = "STUB: not implemented"; return "" }

func (x *State) GetSuccessfulCycles() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *State) GetConflicts() []*core.Conflict { _ = "STUB: not implemented"; return nil }

func (x *State) GetExcludedConflicts() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *State) GetAlphaState() *EndpointState { _ = "STUB: not implemented"; return nil }

func (x *State) GetBetaState() *EndpointState { _ = "STUB: not implemented"; return nil }

var File_synchronization_state_proto protoreflect.FileDescriptor

const file_synchronization_state_proto_rawDesc = "" +
	"\n" +
	"\x1bsynchronization/state.proto\x12\x0fsynchronization\x1a#synchronization/rsync/receive.proto\x1a\x1dsynchronization/session.proto\x1a#synchronization/core/conflict.proto\x1a\"synchronization/core/problem.proto\"\xf1\x03\n" +
	"\rEndpointState\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x18\n" +
	"\ascanned\x18\x02 \x01(\bR\ascanned\x12 \n" +
	"\vdirectories\x18\x03 \x01(\x04R\vdirectories\x12\x14\n" +
	"\x05files\x18\x04 \x01(\x04R\x05files\x12$\n" +
	"\rsymbolicLinks\x18\x05 \x01(\x04R\rsymbolicLinks\x12$\n" +
	"\rtotalFileSize\x18\x06 \x01(\x04R\rtotalFileSize\x121\n" +
	"\fscanProblems\x18\a \x03(\v2\r.core.ProblemR\fscanProblems\x122\n" +
	"\x14excludedScanProblems\x18\b \x01(\x04R\x14excludedScanProblems\x12=\n" +
	"\x12transitionProblems\x18\t \x03(\v2\r.core.ProblemR\x12transitionProblems\x12>\n" +
	"\x1aexcludedTransitionProblems\x18\n" +
	" \x01(\x04R\x1aexcludedTransitionProblems\x12>\n" +
	"\x0fstagingProgress\x18\v \x01(\v2\x14.rsync.ReceiverStateR\x0fstagingProgress\"\x90\x03\n" +
	"\x05State\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.synchronization.SessionR\asession\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.synchronization.StatusR\x06status\x12\x1c\n" +
	"\tlastError\x18\x03 \x01(\tR\tlastError\x12*\n" +
	"\x10successfulCycles\x18\x04 \x01(\x04R\x10successfulCycles\x12,\n" +
	"\tconflicts\x18\x05 \x03(\v2\x0e.core.ConflictR\tconflicts\x12,\n" +
	"\x11excludedConflicts\x18\x06 \x01(\x04R\x11excludedConflicts\x12>\n" +
	"\n" +
	"alphaState\x18\a \x01(\v2\x1e.synchronization.EndpointStateR\n" +
	"alphaState\x12<\n" +
	"\tbetaState\x18\b \x01(\v2\x1e.synchronization.EndpointStateR\tbetaState*\x97\x02\n" +
	"\x06Status\x12\x10\n" +
	"\fDisconnected\x10\x00\x12\x17\n" +
	"\x13HaltedOnRootEmptied\x10\x01\x12\x18\n" +
	"\x14HaltedOnRootDeletion\x10\x02\x12\x1a\n" +
	"\x16HaltedOnRootTypeChange\x10\x03\x12\x13\n" +
	"\x0fConnectingAlpha\x10\x04\x12\x12\n" +
	"\x0eConnectingBeta\x10\x05\x12\f\n" +
	"\bWatching\x10\x06\x12\f\n" +
	"\bScanning\x10\a\x12\x14\n" +
	"\x10WaitingForRescan\x10\b\x12\x0f\n" +
	"\vReconciling\x10\t\x12\x10\n" +
	"\fStagingAlpha\x10\n" +
	"\x12\x0f\n" +
	"\vStagingBeta\x10\v\x12\x11\n" +
	"\rTransitioning\x10\f\x12\n" +
	"\n" +
	"\x06Saving\x10\rB3Z1github.com/mutagen-io/mutagen/pkg/synchronizationb\x06proto3"

var (
	file_synchronization_state_proto_rawDescOnce sync.Once
	file_synchronization_state_proto_rawDescData []byte
)

func file_synchronization_state_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_synchronization_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_synchronization_state_proto_goTypes = []any{
	(Status)(0),                 // 0: synchronization.Status
	(*EndpointState)(nil),       // 1: synchronization.EndpointState
	(*State)(nil),               // 2: synchronization.State
	(*core.Problem)(nil),        // 3: core.Problem
	(*rsync.ReceiverState)(nil), // 4: rsync.ReceiverState
	(*Session)(nil),             // 5: synchronization.Session
	(*core.Conflict)(nil),       // 6: core.Conflict
}
var file_synchronization_state_proto_depIdxs = []int32{
	3, // 0: synchronization.EndpointState.scanProblems:type_name -> core.Problem
	3, // 1: synchronization.EndpointState.transitionProblems:type_name -> core.Problem
	4, // 2: synchronization.EndpointState.stagingProgress:type_name -> rsync.ReceiverState
	5, // 3: synchronization.State.session:type_name -> synchronization.Session
	0, // 4: synchronization.State.status:type_name -> synchronization.Status
	6, // 5: synchronization.State.conflicts:type_name -> core.Conflict
	1, // 6: synchronization.State.alphaState:type_name -> synchronization.EndpointState
	1, // 7: synchronization.State.betaState:type_name -> synchronization.EndpointState
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init()                                  { file_synchronization_state_proto_init() }
func file_synchronization_state_proto_init() { _ = "STUB: not implemented"; return }
