// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: synchronization/watch_mode.proto

package synchronization

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WatchMode specifies the mode for filesystem watching.
type WatchMode int32

const (
	// WatchMode_WatchModeDefault represents an unspecified watch mode. It
	// should be converted to one of the following values based on the desired
	// default behavior.
	WatchMode_WatchModeDefault WatchMode = 0
	// WatchMode_WatchModePortable specifies that native recursive watching
	// should be used to monitor paths on systems that support it if those paths
	// fall under the home directory. In these cases, a watch on the entire home
	// directory is established and filtered for events pertaining to the
	// specified path. On all other systems and for all other paths, poll-based
	// watching is used.
	WatchMode_WatchModePortable WatchMode = 1
	// WatchMode_WatchModeForcePoll specifies that only poll-based watching
	// should be used.
	WatchMode_WatchModeForcePoll WatchMode = 2
	// WatchMode_WatchModeNoWatch specifies that no watching should be used
	// (i.e. no events should be generated).
	WatchMode_WatchModeNoWatch WatchMode = 3
)

// Enum value maps for WatchMode.
var (
	WatchMode_name = map[int32]string{
		0: "WatchModeDefault",
		1: "WatchModePortable",
		2: "WatchModeForcePoll",
		3: "WatchModeNoWatch",
	}
	WatchMode_value = map[string]int32{
		"WatchModeDefault":   0,
		"WatchModePortable":  1,
		"WatchModeForcePoll": 2,
		"WatchModeNoWatch":   3,
	}
)

func (x WatchMode) Enum() *WatchMode { _ = "STUB: not implemented"; return nil }

func (x WatchMode) String() string { _ = "STUB: not implemented"; return "" }

func (WatchMode) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (WatchMode) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x WatchMode) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use WatchMode.Descriptor instead.
func (WatchMode) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_synchronization_watch_mode_proto protoreflect.FileDescriptor

const file_synchronization_watch_mode_proto_rawDesc = "" +
	"\n" +
	" synchronization/watch_mode.proto\x12\x0fsynchronization*f\n" +
	"\tWatchMode\x12\x14\n" +
	"\x10WatchModeDefault\x10\x00\x12\x15\n" +
	"\x11WatchModePortable\x10\x01\x12\x16\n" +
	"\x12WatchModeForcePoll\x10\x02\x12\x14\n" +
	"\x10WatchModeNoWatch\x10\x03B3Z1github.com/mutagen-io/mutagen/pkg/synchronizationb\x06proto3"

var (
	file_synchronization_watch_mode_proto_rawDescOnce sync.Once
	file_synchronization_watch_mode_proto_rawDescData []byte
)

func file_synchronization_watch_mode_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_synchronization_watch_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_synchronization_watch_mode_proto_goTypes = []any{
	(WatchMode)(0), // 0: synchronization.WatchMode
}
var file_synchronization_watch_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                       { file_synchronization_watch_mode_proto_init() }
func file_synchronization_watch_mode_proto_init() { _ = "STUB: not implemented"; return }
